// <auto-generated />
using System;
using InsideAirbnb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsideAirbnb.Migrations
{
    [DbContext(typeof(InsideAirbnbContext))]
    partial class InsideAirbnbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InsideAirbnb.Models.Listing", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int?>("Accommodates")
                        .HasColumnType("int")
                        .HasColumnName("accommodates");

                    b.Property<string>("Amenities")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("amenities");

                    b.Property<int?>("Availability30")
                        .HasColumnType("int")
                        .HasColumnName("availability_30");

                    b.Property<int?>("Availability365")
                        .HasColumnType("int")
                        .HasColumnName("availability_365");

                    b.Property<int?>("Availability60")
                        .HasColumnType("int")
                        .HasColumnName("availability_60");

                    b.Property<int?>("Availability90")
                        .HasColumnType("int")
                        .HasColumnName("availability_90");

                    b.Property<string>("Bathrooms")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("bathrooms");

                    b.Property<string>("BathroomsText")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("bathrooms_text");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("int")
                        .HasColumnName("bedrooms");

                    b.Property<int?>("Beds")
                        .HasColumnType("int")
                        .HasColumnName("beds");

                    b.Property<int?>("CalculatedHostListingsCount")
                        .HasColumnType("int")
                        .HasColumnName("calculated_host_listings_count");

                    b.Property<int?>("CalculatedHostListingsCountEntireHomes")
                        .HasColumnType("int")
                        .HasColumnName("calculated_host_listings_count_entire_homes");

                    b.Property<int?>("CalculatedHostListingsCountPrivateRooms")
                        .HasColumnType("int")
                        .HasColumnName("calculated_host_listings_count_private_rooms");

                    b.Property<int?>("CalculatedHostListingsCountSharedRooms")
                        .HasColumnType("int")
                        .HasColumnName("calculated_host_listings_count_shared_rooms");

                    b.Property<string>("CalendarLastScraped")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("calendar_last_scraped");

                    b.Property<string>("CalendarUpdated")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("calendar_updated");

                    b.Property<string>("Description")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("FirstReview")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("first_review");

                    b.Property<string>("HasAvailability")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("has_availability");

                    b.Property<string>("HostAbout")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("host_about");

                    b.Property<string>("HostAcceptanceRate")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("host_acceptance_rate");

                    b.Property<string>("HostHasProfilePic")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("host_has_profile_pic");

                    b.Property<int?>("HostId")
                        .HasColumnType("int")
                        .HasColumnName("host_id");

                    b.Property<string>("HostIdentityVerified")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("host_identity_verified");

                    b.Property<string>("HostIsSuperhost")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("host_is_superhost");

                    b.Property<int?>("HostListingsCount")
                        .HasColumnType("int")
                        .HasColumnName("host_listings_count");

                    b.Property<string>("HostLocation")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("host_location");

                    b.Property<string>("HostName")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("host_name");

                    b.Property<string>("HostNeighbourhood")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("host_neighbourhood");

                    b.Property<string>("HostPictureUrl")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("host_picture_url");

                    b.Property<string>("HostResponseRate")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("host_response_rate");

                    b.Property<string>("HostResponseTime")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("host_response_time");

                    b.Property<string>("HostSince")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("host_since");

                    b.Property<string>("HostThumbnailUrl")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("host_thumbnail_url");

                    b.Property<int?>("HostTotalListingsCount")
                        .HasColumnType("int")
                        .HasColumnName("host_total_listings_count");

                    b.Property<string>("HostUrl")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("host_url");

                    b.Property<string>("HostVerifications")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("host_verifications");

                    b.Property<string>("InstantBookable")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("instant_bookable");

                    b.Property<string>("LastReview")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("last_review");

                    b.Property<string>("LastScraped")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("last_scraped");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("latitude");

                    b.Property<string>("License")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("license");

                    b.Property<string>("ListingUrl")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("listing_url");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("longitude");

                    b.Property<int?>("MaximumMaximumNights")
                        .HasColumnType("int")
                        .HasColumnName("maximum_maximum_nights");

                    b.Property<int?>("MaximumMinimumNights")
                        .HasColumnType("int")
                        .HasColumnName("maximum_minimum_nights");

                    b.Property<int?>("MaximumNights")
                        .HasColumnType("int")
                        .HasColumnName("maximum_nights");

                    b.Property<double?>("MaximumNightsAvgNtm")
                        .HasColumnType("float")
                        .HasColumnName("maximum_nights_avg_ntm");

                    b.Property<int?>("MinimumMaximumNights")
                        .HasColumnType("int")
                        .HasColumnName("minimum_maximum_nights");

                    b.Property<int?>("MinimumMinimumNights")
                        .HasColumnType("int")
                        .HasColumnName("minimum_minimum_nights");

                    b.Property<int?>("MinimumNights")
                        .HasColumnType("int")
                        .HasColumnName("minimum_nights");

                    b.Property<double?>("MinimumNightsAvgNtm")
                        .HasColumnType("float")
                        .HasColumnName("minimum_nights_avg_ntm");

                    b.Property<string>("Name")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("NeighborhoodOverview")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("neighborhood_overview");

                    b.Property<string>("Neighbourhood")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("neighbourhood");

                    b.Property<string>("NeighbourhoodCleansed")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("neighbourhood_cleansed");

                    b.Property<string>("NeighbourhoodGroupCleansed")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("neighbourhood_group_cleansed");

                    b.Property<int?>("NumberOfReviews")
                        .HasColumnType("int")
                        .HasColumnName("number_of_reviews");

                    b.Property<int?>("NumberOfReviewsL30d")
                        .HasColumnType("int")
                        .HasColumnName("number_of_reviews_l30d");

                    b.Property<int?>("NumberOfReviewsLtm")
                        .HasColumnType("int")
                        .HasColumnName("number_of_reviews_ltm");

                    b.Property<string>("PictureUrl")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("picture_url");

                    b.Property<string>("Price")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("price");

                    b.Property<string>("PropertyType")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("property_type");

                    b.Property<double?>("ReviewScoresAccuracy")
                        .HasColumnType("float")
                        .HasColumnName("review_scores_accuracy");

                    b.Property<double?>("ReviewScoresCheckin")
                        .HasColumnType("float")
                        .HasColumnName("review_scores_checkin");

                    b.Property<double?>("ReviewScoresCleanliness")
                        .HasColumnType("float")
                        .HasColumnName("review_scores_cleanliness");

                    b.Property<double?>("ReviewScoresCommunication")
                        .HasColumnType("float")
                        .HasColumnName("review_scores_communication");

                    b.Property<double?>("ReviewScoresLocation")
                        .HasColumnType("float")
                        .HasColumnName("review_scores_location");

                    b.Property<double?>("ReviewScoresRating")
                        .HasColumnType("float")
                        .HasColumnName("review_scores_rating");

                    b.Property<double?>("ReviewScoresValue")
                        .HasColumnType("float")
                        .HasColumnName("review_scores_value");

                    b.Property<double?>("ReviewsPerMonth")
                        .HasColumnType("float")
                        .HasColumnName("reviews_per_month");

                    b.Property<string>("RoomType")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("room_type");

                    b.Property<double?>("ScrapeId")
                        .HasColumnType("float")
                        .HasColumnName("scrape_id");

                    b.HasKey("Id");

                    b.ToTable("listings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
